/**
 * Core domain model for WhatToWear.
 *
 * The closet is a collection of ClothingItems. Outfits are combinations of
 * items chosen for a given Occasion and the current Weather. Everything in the
 * recommendation pipeline keys off these types.
 */

/** Broad slot a garment fills. Drives outfit assembly (one top + one bottom, etc.). */
export type Category =
  | 'top'
  | 'bottom'
  | 'outerwear'
  | 'dress'
  | 'footwear'
  | 'accessory';

export const CATEGORIES: Category[] = [
  'top',
  'bottom',
  'outerwear',
  'dress',
  'footwear',
  'accessory',
];

/** 1 = very casual (gym/lounge) … 5 = black tie. */
export type Formality = 1 | 2 | 3 | 4 | 5;

/** How much warmth a garment provides. 1 = tank/sandals … 5 = heavy winter coat. */
export type Warmth = 1 | 2 | 3 | 4 | 5;

/** The setting the user is dressing for. */
export type Occasion =
  | 'casual'
  | 'work'
  | 'formal'
  | 'leisure'
  | 'date'
  | 'workout';

export const OCCASIONS: { id: Occasion; label: string; icon: string; targetFormality: Formality }[] = [
  { id: 'casual', label: 'Casual', icon: 'cafe-outline', targetFormality: 2 },
  { id: 'work', label: 'Work', icon: 'briefcase-outline', targetFormality: 3 },
  { id: 'formal', label: 'Formal', icon: 'sparkles-outline', targetFormality: 5 },
  { id: 'leisure', label: 'Leisure', icon: 'sunny-outline', targetFormality: 2 },
  { id: 'date', label: 'Date', icon: 'heart-outline', targetFormality: 4 },
  { id: 'workout', label: 'Workout', icon: 'barbell-outline', targetFormality: 1 },
];

/** A single garment in the user's closet. */
export interface ClothingItem {
  id: string;
  name: string;
  category: Category;
  /** Finer-grained type, e.g. "oxford shirt", "chinos", "chelsea boots". */
  subtype?: string;
  /** Human color names, primary first, e.g. ["navy", "white"]. */
  colors: string[];
  formality: Formality;
  warmth: Warmth;
  /** Occasions this item is appropriate for. */
  occasions: Occasion[];
  /** Local URI or remote URL of the garment photo. */
  imageUri?: string;
  brand?: string;
  /** Where the item came from. "purchase" items are auto-imported. */
  source: 'manual' | 'purchase';
  createdAt: number;
  lastWornAt?: number;
  favorite?: boolean;
}

/** A proposed combination of items for an occasion + weather. */
export interface Outfit {
  id: string;
  itemIds: string[];
  /** Hydrated items, in display order (top → bottom → shoes → outerwear → accessories). */
  items: ClothingItem[];
  occasion: Occasion;
  /** Short stylist explanation of why these pieces work together. */
  rationale: string;
  /** 0–100 internal fit score used for ranking. */
  score: number;
  /** True when generated by the Claude stylist rather than the rules engine. */
  aiGenerated: boolean;
}

/** Snapshot of current conditions used for warmth/precip decisions. */
export interface Weather {
  tempC: number;
  tempF: number;
  feelsLikeC: number;
  /** Open-Meteo WMO weather code. */
  conditionCode: number;
  /** Human-readable summary, e.g. "Light rain". */
  condition: string;
  /** Probability of precipitation, 0–100. */
  precipitationProb: number;
  windKph: number;
  isDay: boolean;
  highC: number;
  lowC: number;
  locationName?: string;
  fetchedAt: number;
}

/** Attributes Claude (or the user) infers about a garment photo. */
export type InferredItem = Pick<
  ClothingItem,
  'name' | 'category' | 'subtype' | 'colors' | 'formality' | 'warmth' | 'occasions' | 'brand'
>;
